trigger:
- master

pool:
  name: 'agent1'

steps:
- script: cd /home/azureuser/myagent/_work/1/s;mvn package
  displayName: 'Build'
- script: scp /home/azureuser/myagent/_work/1/s/webapp/target/webapp.war azureuser@40.67.146.49:/var/lib/tomcat10/webapps/testapp.war
  displayName: 'Deployment'
- script: git clone https://github.com/IntelliqDevops/FunctionalTesting.git
  displayName: 'Download selenium code'
- script: java -jar /home/azureuser/myagent/_work/1/s/FunctionalTesting/testing.jar
  displayName: 'Run selenium'
- script: scp /home/azureuser/myagent/_work/1/s/webapp/target/webapp.war azureuser@20.81.208.251:/var/lib/tomcat10/webapps/prodapp.war
  displayName: 'Delivery to Prod'